{
 "title": "Lodestar - debug gossipsub",
 "tags": [
  "lodestar",
  "debug"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "rate_interval",
    "label": "rate() interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Peer count per gossip score threshold",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg_over_time( lodestar_gossip_peer_score_by_threshold_count [$rate_interval])",
     "legendFormat": "{{threshold}}"
    }
   ]
  },
  {
   "title": "Validators connected",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "validator_monitor_validators" }
   ]
  },
  {
   "title": "Sync status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lodestar_sync_status" }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lodestar_version", "legendFormat": "{{network}}" }
   ]
  },
  {
   "title": "Lodestar version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lodestar_version", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "NodeJS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_version_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Slot",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "round((time() - lodestar_genesis_time) / 12)",
     "legendFormat": "clock slot"
    },
    { "expr": "beacon_head_slot", "legendFormat": "head slot" },
    {
     "expr": "changes(process_start_time_seconds[5m])",
     "legendFormat": "process restart"
    }
   ]
  },
  {
   "title": "Mesh peers count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg_over_time(lodestar_gossip_mesh_peers_by_type_count{type!~\"beacon_attestation\"}[$rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Gossip score avg / min / max",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "lodestar_gossip_score_avg_min_max_max",
     "legendFormat": "max"
    },
    {
     "expr": "lodestar_gossip_score_avg_min_max_avg",
     "legendFormat": "avg"
    },
    {
     "expr": "lodestar_gossip_score_avg_min_max_min",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Attnet count with > 0 mesh peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "count(lodestar_gossip_mesh_peers_by_beacon_attestation_subnet_count > 0)",
     "legendFormat": "{{subnet}}"
    }
   ]
  },
  {
   "title": "Gossip validation queue - Processed jobs / slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "12*rate(lodestar_gossip_validation_queue_job_time_seconds_count[$rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Gossip validation queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Gossip validation queues - Job wait time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_validation_queue_job_wait_time_seconds_sum[$rate_interval])/rate(lodestar_gossip_validation_queue_job_wait_time_seconds_count[$rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Gossip validation queue - Dropped jobs %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_validation_queue_dropped_jobs_total[$rate_interval])/(rate(lodestar_gossip_validation_queue_job_time_seconds_count[$rate_interval])+rate(lodestar_gossip_validation_queue_dropped_jobs_total[$rate_interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Gossip Block Received Delay",
   "type": "timeseries",
   "description": "Time elapsed between block slot time and the time block received via gossip",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_elapsed_time_till_received_sum{source=\"gossip\"}[$rate_interval])\n/\nrate(lodestar_gossip_block_elapsed_time_till_received_count{source=\"gossip\"}[$rate_interval])",
     "legendFormat": "till received"
    },
    {
     "expr": "rate(lodestar_gossip_block_elapsed_time_till_processed_sum[$rate_interval])\n/\nrate(lodestar_gossip_block_elapsed_time_till_processed_count[$rate_interval])",
     "legendFormat": "till processed"
    }
   ]
  },
  {
   "title": "Gossip validation queues - Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(\n    lodestar_gossip_validation_queue_length\n[$rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Gossipsub - mesh stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Topic peers per topic (subscribed)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    { "expr": "gossipsub_topic_peer_count", "legendFormat": "{{topicStr}}" }
   ]
  },
  {
   "title": "Mesh peers per topic (grafted)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "avg_over_time( gossipsub_mesh_peer_count [$rate_interval])",
     "legendFormat": "{{topicStr}}"
    }
   ]
  },
  {
   "title": "Mesh inclusion (+) / churn (-) events - sum by topic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(gossipsub_mesh_peer_inclusion_events_total[$rate_interval])\n) by (topic)",
     "legendFormat": "+ {{topic}}"
    },
    {
     "expr": "- sum(\n  rate(gossipsub_peer_churn_events_total [$rate_interval])\n) by (topic)",
     "legendFormat": "- {{topic}}"
    }
   ]
  },
  {
   "title": "Mesh inclusion (+) / churn (-) events - sum by reason",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(gossipsub_mesh_peer_inclusion_events_fanout_total[$rate_interval]))",
     "legendFormat": "+ fanout"
    },
    {
     "expr": "sum(rate(gossipsub_mesh_peer_inclusion_events_random_total[$rate_interval]))",
     "legendFormat": "+ random"
    },
    {
     "expr": "sum(rate(gossipsub_mesh_peer_inclusion_events_subscribed_total[$rate_interval]))",
     "legendFormat": "+ subscribed"
    },
    {
     "expr": "sum(rate(gossipsub_mesh_peer_inclusion_events_outbound_total[$rate_interval]))",
     "legendFormat": "+ outbound"
    },
    {
     "expr": "sum(rate(gossipsub_mesh_peer_inclusion_events_not_enough_total[$rate_interval]))",
     "legendFormat": "+ not_enough"
    },
    {
     "expr": "sum(rate(gossipsub_mesh_peer_inclusion_events_opportunistic_total[$rate_interval]))",
     "legendFormat": "+ opportunistic"
    },
    {
     "expr": "- sum(rate(gossipsub_peer_churn_events_disconnected_total[$rate_interval]))",
     "legendFormat": "- disconnected"
    },
    {
     "expr": "- sum(rate(gossipsub_peer_churn_events_bad_score_total[$rate_interval]))",
     "legendFormat": "- bad_score"
    },
    {
     "expr": "- sum(rate(gossipsub_peer_churn_events_prune_total[$rate_interval]))",
     "legendFormat": "- prune"
    },
    {
     "expr": "- sum(rate(gossipsub_peer_churn_events_excess_total[$rate_interval]))",
     "legendFormat": "- excess"
    }
   ]
  },
  {
   "title": "Gossipsub - received message",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Received msg / sec (log)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_msg_received_prevalidation_total[$rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Received msg duplicate / valid rate (except light_* topics)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(gossipsub_pre_validation_duplicate_total{topic!~\"light.*\"} [32m])) by (topic))\n/\n(sum(rate(gossipsub_msg_received_prevalidation_total{topic!~\"light.*\"} [32m])) by (topic))",
     "legendFormat": "{{topic}} {{status}}"
    }
   ]
  },
  {
   "title": "Received VALID msg / sec (log)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_pre_validation_valid_total [$rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Received msg pre-validation / valid rate - by topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(rate(gossipsub_msg_received_prevalidation_total [32m])) by (topic))\n/\n(sum(rate(gossipsub_pre_validation_valid_total [32m])) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Received invalid messages rate (no data = no invalid msgs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_pre_validation_invalid_total[$rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "RPC not accepted from rate (no data = no invalid msgs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_rpc_rcv_not_accepted_total[$rate_interval])"
    }
   ]
  },
  {
   "title": "Async validation result - IGNORE / REJECT rates",
   "type": "timeseries",
   "description": "32 minutes because it's exactly 5 epochs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(gossipsub_ignored_messages_total[32m])) by (topic))\n/\n(\n    sum(rate(gossipsub_msg_received_prevalidation_total[32m])) by (topic)\n)",
     "legendFormat": "IGNORE {{topic}}"
    },
    {
     "expr": "(sum(rate(gossipsub_rejected_messages_total[32m])) by (topic))\n/\n(\n    sum(rate(gossipsub_msg_received_prevalidation_total[32m])) by (topic)\n)",
     "legendFormat": "REJECT {{topic}}"
    },
    {
     "expr": "(sum(rate(gossipsub_unknown_validation_results_total[32m])) by (topic))\n/\n(\n    sum(rate(gossipsub_msg_received_prevalidation_total[32m])) by (topic)\n)",
     "legendFormat": "UNKNOWN {{topic}}"
    }
   ]
  },
  {
   "title": "Async validation result - mcache hit / miss rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_async_validation_mcache_hit_total [$rate_interval])",
     "legendFormat": "{{hit}}"
    }
   ]
  },
  {
   "title": "Gossip Aggregate And Proof Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_validation_error_total{topic=\"beacon_aggregate_and_proof\"}[$rate_interval])",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Gossip DataColumnSidecar Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_validation_error_total{topic=\"data_column_sidecar\"}[$rate_interval])",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Gossipsub - publish / forward",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 103 },
   "options": {
    "content": "<center><strong>\nPublish / Forwarded messages\n</strong>\n</center>"
   }
  },
  {
   "title": "Published msg peerGroups - sum over topics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "sum(rate(gossipsub_msg_publish_peers_by_group[$rate_interval])) by (peerGroup)",
     "legendFormat": "{{peerGroup}}"
    }
   ]
  },
  {
   "title": "Publish msg data bytes / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_msg_publish_bytes_total[$rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Published msg / sec by topic (LOG)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_msg_publish_count_total[$rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Published msg avg peers sent per RPC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(gossipsub_msg_publish_peers_total[$rate_interval])\n/\nrate(gossipsub_msg_publish_count_total[$rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Forward msg / sec by topic (LOG)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "targets": [
    {
     "expr": "rate(gossipsub_msg_forward_count_total[$rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Forward msg avg peers sent per RPC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(gossipsub_msg_forward_peers_total[$rate_interval])\n/\nrate(gossipsub_msg_forward_count_total[$rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Gossipsub - score",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Peers by score threshold",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 130 },
   "targets": [
    {
     "expr": "gossipsub_peers_by_score_threshold_count",
     "legendFormat": "{{threshold}}"
    }
   ]
  },
  {
   "title": "Gossip score avg / min / max",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 130 },
   "targets": [
    { "expr": "gossipsub_score_max", "legendFormat": "max" },
    { "expr": "gossipsub_score_avg", "legendFormat": "avg" },
    { "expr": "gossipsub_score_min", "legendFormat": "min" }
   ]
  },
  {
   "title": "Score weights AVG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "targets": [
    { "expr": "gossipsub_score_weights_avg", "legendFormat": "{{p}} {{topic}}" }
   ]
  },
  {
   "title": "Score weights MIN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
   "targets": [
    { "expr": "gossipsub_score_weights_min", "legendFormat": "{{p}} {{topic}}" }
   ]
  },
  {
   "title": "Score weights AVG (log · > 1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
   "targets": [
    {
     "expr": "gossipsub_score_weights_avg > 1",
     "legendFormat": "{{p}} {{topic}}"
    }
   ]
  },
  {
   "title": "Score weights AVG (inverted · log · > 10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
   "targets": [
    {
     "expr": "- gossipsub_score_weights_avg > 10",
     "legendFormat": "{{p}} {{topic}}"
    }
   ]
  },
  {
   "title": "Mesh score AVG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
   "targets": [
    {
     "expr": "avg_over_time( gossipsub_score_per_mesh_avg [$rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Mesh score MIN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
   "targets": [
    {
     "expr": "avg_over_time( gossipsub_score_per_mesh_min [$rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Gossipsub - score debug P3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 163 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 164 },
   "options": {
    "content": "#### P3 / P3b penalties (delivery rate)\n\nFrom [gossipsub-v1.1 specs](https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#the-score-function),\nP₃ tracks the rate of messages delivered. It's meant to penalize who don't deliver enough messages or do so late.\n\nP₃b persists the difference to the expected threshold to keep a history of bad peers"
   }
  },
  { "type": "text", "gridPos": { "h": 4, "w": 12, "x": 12, "y": 164 } },
  {
   "title": "Gossip score weight P3 avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
   "targets": [
    {
     "expr": "gossipsub_score_weights_avg{p=\"p3\"}",
     "legendFormat": "avg {{topic}}"
    }
   ]
  },
  {
   "title": "Gossip score weight P3b avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 168 },
   "targets": [
    {
     "expr": "gossipsub_score_weights_avg{p=\"p3b\"}",
     "legendFormat": "avg {{topic}}"
    }
   ]
  },
  {
   "title": "Late msg delivery rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
   "targets": [
    {
     "expr": "rate(gossisub_duplicate_msg_late_delivery_total[$rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Late msg delivery / total msg delivery share",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(gossisub_duplicate_msg_late_delivery_total[$rate_interval]))\n/\nsum(rate(gossisub_duplicate_msg_delivery_delay_seconds_count[$rate_interval]))",
     "legendFormat": "late / duplicate"
    }
   ]
  },
  {
   "title": "IWANT promise delivery time histogram > 12",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(gossisub_duplicate_msg_delivery_delay_seconds_bucket{le=\"24\"}[32m]))\n-\nsum(rate(gossisub_duplicate_msg_delivery_delay_seconds_bucket{le=\"12\"}[32m]))",
     "legendFormat": "12 << 24"
    },
    {
     "expr": "sum(rate(gossisub_duplicate_msg_delivery_delay_seconds_bucket{le=\"48\"}[32m]))\n-\nsum(rate(gossisub_duplicate_msg_delivery_delay_seconds_bucket{le=\"24\"}[32m]))",
     "legendFormat": "24 << 48"
    },
    {
     "expr": "sum(rate(gossisub_duplicate_msg_delivery_delay_seconds_bucket{le=\"+Inf\"}[32m]))\n-\nsum(rate(gossisub_duplicate_msg_delivery_delay_seconds_bucket{le=\"48\"}[32m]))",
     "legendFormat": "48 << +Inf"
    }
   ]
  },
  {
   "title": "Duplicate msg delivery delay histogram (exclude lowest value)",
   "type": "heatmap",
   "description": "By shifting the scale by -10000 the lowest bound does not render, if the coloring scheme is strictly positive. Since most of the values are low, the values above the lowest bound won't render",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
   "targets": [
    {
     "expr": "rate(gossisub_duplicate_msg_delivery_delay_seconds_bucket[$rate_interval]) - 10000",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Gossipsub - score debug P7",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 192 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
   "options": {
    "content": "#### P7 penalties (broken IWANT promises)\n\nFrom [gossipsub-v1.1 specs](https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#the-score-function), P₇ is a Behavioural Penalty. Most penalties are due to broken IWANT promises. Our node is informed by a peer that some msgID exists that we don't know so we request it. We track some of those request and expect to receive that msgID within a time window (spec 3s, lodestar 12s @ apr'22)\n\nPeer scores are very sensitive to P7 penalties: `score = -15.8 * p7 ** 2`, they are also very sticky, decaying slowly.\n\n| p7 | score |\n| -- | ----- |\n| 5\t | -395  |\n| 10 | -1580 |\n| 15 | -3555 |\n| 20 | -6320 |\n"
   }
  },
  {
   "title": "Gossip score weight P7 max / avg / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
   "targets": [
    {
     "expr": "gossipsub_score_weights_max{p=\"p7\"}",
     "legendFormat": "max"
    },
    {
     "expr": "gossipsub_score_weights_avg{p=\"p7\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "gossipsub_score_weights_min{p=\"p7\"}",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Score penalties / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_scoring_penalties_total[$rate_interval])",
     "legendFormat": "{{penalty}}"
    }
   ]
  },
  {
   "title": "Gossip score weight P7 avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
   "targets": [
    {
     "expr": "gossipsub_score_weights_avg{p=\"p7\"}",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Peer stat analysis",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 209 },
   "options": {
    "content": "The threshold to start applying penalties is 6, from [lighthouse source](https://github.com/sigp/lighthouse/blob/79db2d4deb6a47947699d8a4a39347c19ee6e5d6/beacon_node/lighthouse_network/src/behaviour/gossipsub_scoring_parameters.rs#L96), peers must have peer_state.behaviour_penalty < 6. Other charts show **how far** from 6 offending peers are."
   }
  },
  {
   "title": "Peers with behaviour_penalty > 6",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 211 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n  sum(gossipsub_peer_stat_behaviour_penalty_bucket{le=\"+Inf\"})\n  -\n  sum(gossipsub_peer_stat_behaviour_penalty_bucket{le=\"6\"})\n)\n/\nsum(gossipsub_peer_stat_behaviour_penalty_bucket{le=\"+Inf\"})",
     "legendFormat": "share of total peers"
    },
    {
     "expr": "sum(gossipsub_peer_stat_behaviour_penalty_bucket{le=\"+Inf\"})\n-\nsum(gossipsub_peer_stat_behaviour_penalty_bucket{le=\"6\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Peer stat behaviour penalties histogram",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 211 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gossipsub_peer_stat_behaviour_penalty_bucket{le=\"1.5\"}",
     "legendFormat": "< 1.5"
    },
    {
     "expr": "sum(gossipsub_peer_stat_behaviour_penalty_bucket{le=\"3\"}) - sum(gossipsub_peer_stat_behaviour_penalty_bucket{le=\"1.5\"})",
     "legendFormat": "1.5 << 3"
    },
    {
     "expr": "sum(gossipsub_peer_stat_behaviour_penalty_bucket{le=\"6\"}) - sum(gossipsub_peer_stat_behaviour_penalty_bucket{le=\"3\"})",
     "legendFormat": "3 << 6"
    },
    {
     "expr": "sum(gossipsub_peer_stat_behaviour_penalty_bucket{le=\"12\"}) - sum(gossipsub_peer_stat_behaviour_penalty_bucket{le=\"6\"})",
     "legendFormat": "6 << 12"
    },
    {
     "expr": "sum(gossipsub_peer_stat_behaviour_penalty_bucket{le=\"24\"}) - sum(gossipsub_peer_stat_behaviour_penalty_bucket{le=\"12\"})",
     "legendFormat": "12 << 24"
    },
    {
     "expr": "sum(gossipsub_peer_stat_behaviour_penalty_bucket{le=\"+Inf\"}) - sum(gossipsub_peer_stat_behaviour_penalty_bucket{le=\"24\"})",
     "legendFormat": "24 << +Inf"
    }
   ]
  },
  {
   "title": "Peers with behaviour_penalty > 3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(gossipsub_peer_stat_behaviour_penalty_bucket{le=\"6\"})\n-\nsum(gossipsub_peer_stat_behaviour_penalty_bucket{le=\"3\"})",
     "legendFormat": "3 << 6"
    },
    {
     "expr": "sum(gossipsub_peer_stat_behaviour_penalty_bucket{le=\"+Inf\"})\n-\nsum(gossipsub_peer_stat_behaviour_penalty_bucket{le=\"6\"})",
     "legendFormat": "6 << +Inf"
    }
   ]
  },
  {
   "title": "Peer stat behaviour penalties histogram (exclude lowest value)",
   "type": "heatmap",
   "description": "By shifting the scale by -100 the lowest bound does not render, if the coloring scheme is strictly positive. Since most of the values are low, the values above the lowest bound won't render",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 219 },
   "targets": [
    {
     "expr": "gossipsub_peer_stat_behaviour_penalty_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Broken promises analysis",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 227 },
   "options": {
    "content": "Understand if promises are actually broken, and by how much. Gossipsub tracks the promise delivery time x10 beyond the time limit for scoring"
   }
  },
  {
   "title": "gossipsub_iwant_promise broken ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 229 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(gossipsub_iwant_promise_sent_total[$rate_interval])",
     "legendFormat": "sent"
    },
    {
     "expr": "rate(gossipsub_iwant_promise_resolved_total[$rate_interval])",
     "legendFormat": "resolved"
    },
    {
     "expr": "rate(gossipsub_iwant_promise_broken[$rate_interval])",
     "legendFormat": "broken"
    },
    {
     "expr": "rate(gossipsub_iwant_promise_broken[$rate_interval])/rate(gossipsub_iwant_promise_sent_total[$rate_interval])",
     "legendFormat": "broken ratio"
    }
   ]
  },
  {
   "title": "gossipsub_iwant_promise broken ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 229 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(gossipsub_iwant_promise_delivery_seconds_bucket{le=\"+Inf\"}[32m]))\n-\nsum(rate(gossipsub_iwant_promise_delivery_seconds_bucket{le=\"12.0\"}[32m]))",
     "legendFormat": "late"
    },
    {
     "expr": "1 - sum(rate(gossipsub_iwant_promise_delivery_seconds_count[$rate_interval])) / sum(rate(gossipsub_iwant_promise_sent_total[$rate_interval]))",
     "legendFormat": "never delivered"
    },
    {
     "expr": "(\n  sum(rate(gossipsub_iwant_promise_delivery_seconds_bucket{le=\"+Inf\"}[32m]))\n  -\n  sum(rate(gossipsub_iwant_promise_delivery_seconds_bucket{le=\"48.0\"}[32m]))\n)\n/\nsum(rate(gossipsub_iwant_promise_broken[$rate_interval]))",
     "legendFormat": "never / broken ratio"
    }
   ]
  },
  {
   "title": "IWANT promise delivery time histogram > 12",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 237 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(gossipsub_iwant_promise_delivery_seconds_bucket{le=\"24\"}[32m]))\n-\nsum(rate(gossipsub_iwant_promise_delivery_seconds_bucket{le=\"12\"}[32m]))",
     "legendFormat": "12 << 24"
    },
    {
     "expr": "sum(rate(gossipsub_iwant_promise_delivery_seconds_bucket{le=\"48\"}[32m]))\n-\nsum(rate(gossipsub_iwant_promise_delivery_seconds_bucket{le=\"24\"}[32m]))",
     "legendFormat": "24 << 48"
    },
    {
     "expr": "sum(rate(gossipsub_iwant_promise_delivery_seconds_bucket{le=\"+Inf\"}[32m]))\n-\nsum(rate(gossipsub_iwant_promise_delivery_seconds_bucket{le=\"48\"}[32m]))",
     "legendFormat": "48 << +Inf"
    }
   ]
  },
  {
   "title": "IWANT promise delivery time seconds",
   "type": "heatmap",
   "description": "By shifting the scale by -100 the lowest bound does not render, if the coloring scheme is strictly positive. Since most of the values are low, the values above the lowest bound won't render",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 237 },
   "targets": [
    {
     "expr": "rate(gossipsub_iwant_promise_delivery_seconds_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "IWANT promise delivery time histogram > 48",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 245 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(gossipsub_iwant_promise_delivery_seconds_bucket{le=\"+Inf\"}[32m]))\n-\nsum(rate(gossipsub_iwant_promise_delivery_seconds_bucket{le=\"48\"}[32m]))",
     "legendFormat": "48 << +Inf"
    }
   ]
  },
  {
   "title": "IWANT promise delivery time histogram > 6",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 245 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(gossipsub_iwant_promise_delivery_seconds_bucket{le=\"12\"}[32m]))\n-\nsum(rate(gossipsub_iwant_promise_delivery_seconds_bucket{le=\"6\"}[32m]))",
     "legendFormat": "6 << 12"
    },
    {
     "expr": "sum(rate(gossipsub_iwant_promise_delivery_seconds_bucket{le=\"24\"}[32m]))\n-\nsum(rate(gossipsub_iwant_promise_delivery_seconds_bucket{le=\"12\"}[32m]))",
     "legendFormat": "12 << 24"
    },
    {
     "expr": "sum(rate(gossipsub_iwant_promise_delivery_seconds_bucket{le=\"48\"}[32m]))\n-\nsum(rate(gossipsub_iwant_promise_delivery_seconds_bucket{le=\"24\"}[32m]))",
     "legendFormat": "24 << 48"
    },
    {
     "expr": "sum(rate(gossipsub_iwant_promise_delivery_seconds_bucket{le=\"+Inf\"}[32m]))\n-\nsum(rate(gossipsub_iwant_promise_delivery_seconds_bucket{le=\"48\"}[32m]))",
     "legendFormat": "48 << +Inf"
    }
   ]
  },
  {
   "title": "Gossipsub - control debug",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 253 },
   "targets": [
    {}
   ]
  },
  {
   "title": "IHAVE received ignored by reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 254 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_ihave_rcv_ignored_total[$rate_interval])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "IHAVE received by topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 254 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_ihave_rcv_msgids_total[$rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "IHAVE received we don't have",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 262 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_ihave_rcv_not_seen_msgids_total[$rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "IHAVE received we don't have / IHAVE received rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 262 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(gossipsub_ihave_rcv_not_seen_msgids_total[$rate_interval])\n/\nrate(gossipsub_ihave_rcv_msgids_total[$rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "IWANT received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 270 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_iwant_rcv_msgids_total[$rate_interval])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "IWANT received we don't have",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 270 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_iwant_rcv_dont_have_msgids_total[$rate_interval])",
     "legendFormat": "rate"
    },
    {
     "expr": "sum(rate(gossipsub_iwant_rcv_dont_have_msgids_total[$rate_interval]))\n/\nsum(rate(gossipsub_iwant_rcv_msgids_total[$rate_interval]))",
     "legendFormat": "share of received"
    }
   ]
  },
  {
   "title": "IDONTWANT sent / received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 278 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_rpc_sent_idontwant_total[$rate_interval])",
     "legendFormat": "sent"
    },
    {
     "expr": "rate(gossipsub_idontwant_rcv_msgids_total[$rate_interval])",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "IDONTWANT received we don't have",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 278 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_idontwant_rcv_dont_have_msgids_total[$rate_interval])",
     "legendFormat": "rate"
    },
    {
     "expr": "sum(rate(gossipsub_idontwant_rcv_dont_have_msgids_total[$rate_interval]))\n/\nsum(rate(gossipsub_idontwant_rcv_msgids_total[$rate_interval]))",
     "legendFormat": "share of received"
    }
   ]
  },
  {
   "title": "Gossipsub - misc, heartbeat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 286 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Gossipsub heartbeat duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 287 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(gossipsub_heartbeat_duration_seconds_sum[$rate_interval])/rate(gossipsub_heartbeat_duration_seconds_count[$rate_interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(gossipsub_heartbeat_duration_seconds_bucket[$rate_interval])) by (le))",
     "legendFormat": "75q"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(gossipsub_heartbeat_duration_seconds_bucket[$rate_interval])) by (le))",
     "legendFormat": "90q"
    }
   ]
  },
  {
   "title": "Gossipsub heartbeat runs / skips per second",
   "type": "timeseries",
   "description": "If skipped: heartbeat run took longer than heartbeat interval so next is skipped. This is bad and should not happen.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 287 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_heartbeat_duration_seconds_count[$rate_interval])",
     "legendFormat": "runs"
    },
    {
     "expr": "rate(gossipsub_heartbeat_skipped[$rate_interval])",
     "legendFormat": "skips"
    }
   ]
  },
  {
   "title": "Cache sizes",
   "type": "timeseries",
   "description": "Increasing lines = memory leak = BAD",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 295 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "gossipsub_cache_size", "legendFormat": "{{cache}}" }
   ]
  },
  {
   "title": "Cache sizes (log)",
   "type": "timeseries",
   "description": "Increasing lines = memory leak = BAD",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 295 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "gossipsub_cache_size", "legendFormat": "{{cache}}" }
   ]
  },
  {
   "title": "Score fn runs / cached calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 303 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_score_fn_calls_total[$rate_interval])",
     "legendFormat": "calls"
    },
    {
     "expr": "rate(gossipsub_score_fn_runs_total[$rate_interval])",
     "legendFormat": "runs"
    },
    {
     "expr": "rate(gossipsub_score_fn_runs_total[$rate_interval])\n/\nrate(gossipsub_score_fn_calls_total[$rate_interval])",
     "legendFormat": "runs / calls"
    }
   ]
  },
  {
   "title": "Score fn delta on run (log)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 303 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(gossipsub_score_cache_delta_sum[$rate_interval])/rate(gossipsub_score_cache_delta_count[$rate_interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(gossipsub_score_cache_delta_bucket[$rate_interval])) by (le))",
     "legendFormat": "75q"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gossipsub_score_cache_delta_bucket[$rate_interval])) by (le))",
     "legendFormat": "95q"
    }
   ]
  },
  {
   "title": "Gossipsub - RPC sent/recv details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 311 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 312 },
   "options": {
    "content": "**Detailed stats about RPC recv / sent**\n\n- Big asymmetries between recv and sent indicate that our node this node is behaving too differently from its peers. RPC behaviour _should_ be mostly symmetrical.\n- As of Apr 2022, Lodestar seem to sends more GRAFTs than receives and receives more PRUNE than it sends. This indicates issues to maintain mesh peers."
   }
  },
  {
   "title": "Gossipsub RPC transmitted bytes / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 316 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_rpc_recv_bytes_total[$rate_interval])",
     "legendFormat": "recv"
    },
    {
     "expr": "-rate(gossipsub_rpc_sent_bytes_total[$rate_interval])",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Gossipsub RPCs transmitted / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 316 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_rpc_recv_count_total[$rate_interval])",
     "legendFormat": "recv"
    },
    {
     "expr": "-rate(gossipsub_rpc_sent_count_total[$rate_interval])",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Gossipsub RPCs subscriptions / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 324 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_rpc_recv_subscription_total[$rate_interval])",
     "legendFormat": "recv"
    },
    {
     "expr": "-rate(gossipsub_rpc_sent_subscription_total[$rate_interval])",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Gossipsub RPCs messages / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 324 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_rpc_recv_message_total[$rate_interval])",
     "legendFormat": "recv"
    },
    {
     "expr": "-rate(gossipsub_rpc_sent_message_total[$rate_interval])",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Gossipsub RPCs control / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 332 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_rpc_recv_control_total[$rate_interval])",
     "legendFormat": "recv"
    },
    {
     "expr": "-rate(gossipsub_rpc_sent_control_total[$rate_interval])",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Gossipsub RPCs control / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 332 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_rpc_recv_control_total[$rate_interval])",
     "legendFormat": "recv"
    },
    {
     "expr": "-rate(gossipsub_rpc_sent_control_total[$rate_interval])",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Gossipsub RPCs IHAVE / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 340 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_rpc_recv_ihave_total[$rate_interval])",
     "legendFormat": "recv"
    },
    {
     "expr": "-rate(gossipsub_rpc_sent_ihave_total[$rate_interval])",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Gossipsub RPCs IWANT / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 340 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_rpc_recv_iwant_total[$rate_interval])",
     "legendFormat": "recv"
    },
    {
     "expr": "-rate(gossipsub_rpc_sent_iwant_total[$rate_interval])",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Gossipsub RPCs GRAFT / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 348 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_rpc_recv_graft_total[$rate_interval])",
     "legendFormat": "recv"
    },
    {
     "expr": "-rate(gossipsub_rpc_sent_graft_total[$rate_interval])",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Gossipsub RPCs PRUNE / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 348 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(gossipsub_rpc_recv_prune_total[$rate_interval])",
     "legendFormat": "recv"
    },
    {
     "expr": "-rate(gossipsub_rpc_sent_prune_total[$rate_interval])",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Gossipsub RPCs avg messages / RPC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 356 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(gossipsub_rpc_recv_message_total[$rate_interval])\n/\nrate(gossipsub_rpc_recv_count_total[$rate_interval])",
     "legendFormat": "recv"
    },
    {
     "expr": "- rate(gossipsub_rpc_sent_message_total[$rate_interval])\n/\nrate(gossipsub_rpc_sent_count_total[$rate_interval])",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Gossipsub RPCs avg control / RPC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 356 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(gossipsub_rpc_recv_control_total[$rate_interval])\n/\nrate(gossipsub_rpc_recv_count_total[$rate_interval])",
     "legendFormat": "recv"
    },
    {
     "expr": "- rate(gossipsub_rpc_sent_control_total[$rate_interval])\n/\nrate(gossipsub_rpc_sent_count_total[$rate_interval])",
     "legendFormat": "sent"
    }
   ]
  }
 ]
}