{
 "title": "Lodestar - sync",
 "tags": [ "lodestar" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "rate_interval",
    "label": "rate() interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Sync - Range",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sync range peers by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "lodestar_sync_range_sync_peers", "legendFormat": "{{syncType}}" },
    {
     "expr": "lodestar_peers_sync_count - sum(lodestar_sync_range_sync_peers)",
     "legendFormat": "Non-sync"
    }
   ]
  },
  {
   "title": "Sync status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "lodestar_sync_status", "legendFormat": "status" }
   ]
  },
  {
   "title": "Switch gossip subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(lodestar_sync_switch_gossip_subscriptions[$rate_interval])",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Sync chain count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "lodestar_sync_chains_count", "legendFormat": "{{syncType}}" }
   ]
  },
  {
   "title": "Sync chains events",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "rate(lodestar_sync_chains_events_total[$rate_interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Total peers in sync chains by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "lodestar_sync_chains_peer_count_by_type_sum",
     "legendFormat": "{{syncType}}"
    }
   ]
  },
  {
   "title": "highest_target_slot_completed - head_slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "(lodestar_sync_chain_highest_target_slot_completed > 0) - beacon_head_slot",
     "legendFormat": "highest_target_slot"
    },
    {
     "expr": "32*beacon_finalized_epoch - beacon_head_slot",
     "legendFormat": "finalized slot"
    }
   ]
  },
  {
   "title": "Sync - Unknown Block",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Actions / slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "12 * rate(lodestar_sync_unknown_block_requests_total[6m])",
     "legendFormat": "{{type}} requests"
    },
    {
     "expr": "12 * rate(lodestar_sync_unknown_block_processed_blocks_success_total[6m])",
     "legendFormat": "processed"
    },
    {
     "expr": "12 * rate(lodestar_sync_unknown_block_downloaded_blocks_success_total[6m])",
     "legendFormat": "downloaded"
    }
   ]
  },
  {
   "title": "Received Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(lodestar_sync_unknown_block_elapsed_time_till_received_bucket{le=\"0.5\"}[$rate_interval]))\n/\nsum(rate(lodestar_sync_unknown_block_elapsed_time_till_received_count[$rate_interval]))",
     "legendFormat": "<=0.5s"
    },
    {
     "expr": "sum(rate(lodestar_sync_unknown_block_elapsed_time_till_received_bucket{le=\"1\"}[$rate_interval]))\n/\nsum(rate(lodestar_sync_unknown_block_elapsed_time_till_received_count[$rate_interval]))",
     "legendFormat": "<=1s"
    },
    {
     "expr": "sum(rate(lodestar_sync_unknown_block_elapsed_time_till_received_bucket{le=\"2\"}[$rate_interval]))\n/\nsum(rate(lodestar_sync_unknown_block_elapsed_time_till_received_count[$rate_interval]))",
     "legendFormat": "<=2s"
    },
    {
     "expr": "sum(rate(lodestar_sync_unknown_block_elapsed_time_till_received_bucket{le=\"4\"}[$rate_interval]))\n/\nsum(rate(lodestar_sync_unknown_block_elapsed_time_till_received_count[$rate_interval]))",
     "legendFormat": "<=4s"
    },
    {
     "expr": "sum(rate(lodestar_sync_unknown_block_elapsed_time_till_received_bucket{le=\"6\"}[$rate_interval]))\n/\nsum(rate(lodestar_sync_unknown_block_elapsed_time_till_received_count[$rate_interval]))",
     "legendFormat": "<=6s"
    },
    {
     "expr": "sum(rate(lodestar_sync_unknown_block_elapsed_time_till_received_bucket{le=\"12\"}[$rate_interval]))\n/\nsum(rate(lodestar_sync_unknown_block_elapsed_time_till_received_count[$rate_interval]))",
     "legendFormat": "<=12s"
    }
   ]
  },
  {
   "title": "Errors / slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "12 * rate(lodestar_sync_unknown_block_processed_blocks_error_total[6m])",
     "legendFormat": "process errors"
    },
    {
     "expr": "12 * rate(lodestar_sync_unknown_block_downloaded_blocks_error_total[6m])",
     "legendFormat": "download errors"
    }
   ]
  },
  {
   "title": "Blocks cache size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "lodestar_sync_unknown_block_pending_blocks_size",
     "legendFormat": "pending blocks"
    },
    {
     "expr": "lodestar_sync_unknown_block_known_bad_blocks_size",
     "legendFormat": "known bad blocks"
    }
   ]
  },
  {
   "title": "Fetch Time And Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_sync_unknown_block_fetch_begin_since_slot_start_seconds_sum[$rate_interval])\n/\nrate(lodestar_sync_unknown_block_fetch_begin_since_slot_start_seconds_count[$rate_interval])",
     "legendFormat": "fetch_begin"
    },
    {
     "expr": "rate(lodestar_sync_unknown_block_fetch_time_seconds_sum[$rate_interval])\n/\nrate(lodestar_sync_unknown_block_fetch_time_seconds_count[$rate_interval])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Removed bad blocks / slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "12 * rate(lodestar_sync_unknown_block_removed_blocks_total[6m])"
    }
   ]
  },
  {
   "title": "Fetch Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "lodestar_sync_unknown_block_fetch_peers_count",
     "legendFormat": "{{result}}"
    }
   ]
  },
  { "title": "Prune History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Fetch Keys",
   "type": "heatmap",
   "description": "Time to fetch keys (for deletion) in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "rate(lodestar_prune_history_fetch_keys_time_seconds_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Prune Keys",
   "type": "heatmap",
   "description": "Time to prune keys in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "rate(lodestar_prune_history_prune_keys_time_seconds_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Sync - Backfill",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Backfill Sync Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "lodestar_backfill_sync_status", "legendFormat": "status" }
   ]
  },
  {
   "title": "Backfilled Till",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    { "expr": "lodestar_backfill_till_slot", "legendFormat": "last backfilled slot" },
    {
     "expr": "lodestar_backfill_prev_fin_or_ws_slot",
     "legendFormat": "prev finalized or ws slot for validation"
    }
   ]
  },
  {
   "title": "Backfill Block Sync Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "rate(lodestar_backfill_sync_blocks_total[$rate_interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Backfill Sync Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "rate(lodestar_backfill_sync_errors_total[$rate_interval])"
    }
   ]
  },
  { "title": "Sync - Unknown Chain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Unknown chain count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "lodestar_unknown_chain_sync_chain_count",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Unknown header count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "lodestar_unknown_chain_sync_header_count",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Headers per chain",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "rate(lodestar_unknown_chain_sync_chain_headers_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Peers per chain",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "targets": [
    {
     "expr": "rate(lodestar_unknown_chain_sync_chain_peers_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Job queue length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "lodestar_unknown_chain_sync_processor_queue_length",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "targets": [
    {
     "expr": "lodestar_unknown_chain_sync_processor_queue_concurrency",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "rate(lodestar_unknown_chain_sync_processor_queue_job_time_seconds_bucket[$rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job wait time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "targets": [
    {
     "expr": "rate(lodestar_unknown_chain_sync_processor_queue_job_wait_time_seconds_bucket[$rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}