{
 "title": "Lodestar - libp2p",
 "tags": [ "lodestar" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "rate_interval",
    "label": "rate() interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "libp2p_connection_manager_connections",
     "legendFormat": "{{libp2p_connection_manager_connections}}"
    }
   ]
  },
  {
   "title": "Inbound Connections by Transport",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "libp2p_tcp_inbound_connections_total",
     "legendFormat": "tcp"
    },
    {
     "expr": "libp2p_quic_inbound_connections_total",
     "legendFormat": "quic"
    }
   ]
  },
  {
   "title": "Dial Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "libp2p_dial_queue", "legendFormat": "{{libp2p_dial_queue}}" }
   ]
  },
  {
   "title": "Streams Per Connection (90th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "libp2p_connection_manager_protocol_streams_per_connection_90th_percentile",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(libp2p_data_transfer_bytes_total[$rate_interval])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Total Streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "libp2p_protocol_streams_total", "legendFormat": "{{protocol}}" }
   ]
  },
  { "title": "QUIC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Dialer Event Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(libp2p_quic_dialer_events_total[$rate_interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Listener Event Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(libp2p_quic_listener_events_total[$rate_interval])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "TCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dialer Event Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(libp2p_tcp_dialer_events_total[$rate_interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Listener Event Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "rate(libp2p_tcp_listener_events_total[$rate_interval])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Listener Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libp2p_tcp_listener_status_info",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Listener Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "rate(libp2p_tcp_listener_errors_total[$rate_interval])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Noise",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Handshake Outcome Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "outcomes/interval" } },
   "targets": [
    {
     "expr": "rate(libp2p_noise_xxhandshake_successes_total[$rate_interval])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(libp2p_noise_xxhandshake_error_total[$rate_interval])",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Packet Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "packets/interval" } },
   "targets": [
    {
     "expr": "rate(libp2p_noise_encrypted_packets_total[$rate_interval])",
     "legendFormat": "encrypted"
    },
    {
     "expr": "rate(libp2p_noise_decrypted_packets_total[$rate_interval])",
     "legendFormat": "decrypted"
    }
   ]
  },
  {
   "title": "Packet Decryption Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "errors/interval" } },
   "targets": [
    {
     "expr": "rate(libp2p_noise_decrypt_errors_total[$rate_interval])",
     "legendFormat": "Decryption Errors"
    }
   ]
  },
  {
   "title": "Packet Decryption Error Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(libp2p_noise_decrypt_errors_total[$rate_interval]) / rate(libp2p_noise_decrypted_packets_total[$rate_interval])",
     "legendFormat": "Decryption Error Percentage"
    }
   ]
  }
 ]
}