{
 "title": "Lodestar - block processor",
 "tags": [ "lodestar" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "rate_interval",
    "label": "rate() interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" },
   { "name": "beacon_job", "label": "Beacon node job name", "query": "${VAR_BEACON_JOB}" }
  ]
 },
 "panels": [
  {
   "title": "Block processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block processor queue - Utilization rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(lodestar_block_processor_queue_job_time_seconds_sum[$rate_interval])",
     "legendFormat": "block_processor"
    }
   ]
  },
  {
   "title": "Block processor queue - Jobs / slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "12*rate(lodestar_block_processor_queue_job_time_seconds_count[6m])",
     "legendFormat": "block_processor"
    }
   ]
  },
  {
   "title": "Block processor queue - Job time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_block_processor_queue_job_time_seconds_sum[$rate_interval])/rate(lodestar_block_processor_queue_job_time_seconds_count[$rate_interval])",
     "legendFormat": "block_processor"
    }
   ]
  },
  {
   "title": "Block processor queue - Dropped jobs %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(lodestar_block_processor_queue_dropped_jobs_total[$rate_interval])/(rate(lodestar_block_processor_queue_job_time_seconds_count[$rate_interval])+rate(lodestar_block_processor_queue_dropped_jobs_total[$rate_interval]))",
     "legendFormat": "block_processor"
    }
   ]
  },
  {
   "title": "Block processor queue - Job wait time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_block_processor_queue_job_wait_time_seconds_sum[$rate_interval])/rate(lodestar_block_processor_queue_job_wait_time_seconds_count[$rate_interval])",
     "legendFormat": "block_processor"
    }
   ]
  },
  {
   "title": "Block processor queue - Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lodestar_block_processor_queue_length",
     "legendFormat": "block_processor"
    }
   ]
  },
  {
   "title": "State transition fn nodes populated cache miss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(lodestar_stfn_balances_nodes_populated_miss_total{source=\"processSlots\"} [$rate_interval])\n/\nrate(lodestar_stfn_state_clone_total[$rate_interval])",
     "legendFormat": "balances-{{source}}"
    },
    {
     "expr": "rate(lodestar_stfn_balances_nodes_populated_miss_total{source=\"stateTransition\"} [$rate_interval])\n/\nrate(lodestar_stfn_state_clone_total[$rate_interval])",
     "legendFormat": "balances-{{source}}"
    },
    {
     "expr": "rate(lodestar_stfn_validators_nodes_populated_miss_total{source=\"processSlots\"} [$rate_interval])\n/\nrate(lodestar_stfn_state_clone_total[$rate_interval])",
     "legendFormat": "validators-{{source}}"
    },
    {
     "expr": "rate(lodestar_stfn_validators_nodes_populated_miss_total{source=\"stateTransition\"} [$rate_interval])\n/\nrate(lodestar_stfn_state_clone_total[$rate_interval])",
     "legendFormat": "validators-{{source}}"
    }
   ]
  },
  {
   "title": "Clone count per state",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(lodestar_stfn_state_cloned_count_bucket[$rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Beacon state transition",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Epoch transition time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "32*12*rate(lodestar_stfn_epoch_transition_seconds_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Process block time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "12*rate(lodestar_stfn_process_block_seconds_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Epoch transition avg time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_stfn_epoch_transition_seconds_sum[$rate_interval])\n/\nrate(lodestar_stfn_epoch_transition_seconds_count[$rate_interval])",
     "legendFormat": "epoch transition"
    }
   ]
  },
  {
   "title": "Process block avg time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_stfn_process_block_seconds_sum[$rate_interval])\n/\nrate(lodestar_stfn_process_block_seconds_count[$rate_interval])",
     "legendFormat": "process block time"
    }
   ]
  },
  {
   "title": "Epoch Transition By Steps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_stfn_epoch_transition_step_seconds_sum[$rate_interval])\n/\nrate(lodestar_stfn_epoch_transition_step_seconds_count[$rate_interval])",
     "legendFormat": "{{step}}"
    }
   ]
  },
  {
   "title": "Process block commit step avg time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_stfn_process_block_commit_seconds_sum[$rate_interval])\n/\nrate(lodestar_stfn_process_block_commit_seconds_count[$rate_interval])",
     "legendFormat": "process block time"
    }
   ]
  },
  {
   "title": "Epoch transition commit step avg time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_stfn_epoch_transition_commit_seconds_sum[$rate_interval])\n/\nrate(lodestar_stfn_epoch_transition_commit_seconds_count[$rate_interval])",
     "legendFormat": "epoch transition"
    }
   ]
  },
  {
   "title": "Process block utilization rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(lodestar_stfn_process_block_seconds_sum[6m])",
     "legendFormat": "process block time"
    }
   ]
  },
  {
   "title": "Epoch transition utilization rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(lodestar_stfn_epoch_transition_seconds_sum[13m])",
     "legendFormat": "process block time"
    }
   ]
  },
  {
   "title": "process block / slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "12*rate(lodestar_stfn_process_block_seconds_count[6m])",
     "legendFormat": "process block time"
    }
   ]
  },
  {
   "title": "Epoch transitions / epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "384 * rate(lodestar_stfn_epoch_transition_seconds_count[13m])",
     "legendFormat": "number of epoch transition"
    }
   ]
  },
  {
   "title": "State SSZ cache miss rate on preState",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(lodestar_stfn_validators_nodes_populated_miss_total{source=\"stateTransition\"} [$rate_interval])\n/on(instance)\nrate(lodestar_stfn_state_cloned_count_count[$rate_interval])",
     "legendFormat": "stateTransition-validators"
    },
    {
     "expr": "rate(lodestar_stfn_balances_nodes_populated_miss_total{source=\"stateTransition\"} [$rate_interval])\n/on(instance)\nrate(lodestar_stfn_state_cloned_count_count[$rate_interval])",
     "legendFormat": "stateTransition-balances"
    },
    {
     "expr": "rate(lodestar_stfn_validators_nodes_populated_miss_total{source=\"processSlots\"} [$rate_interval])\n/on(instance)\nrate(lodestar_stfn_state_cloned_count_count[$rate_interval])",
     "legendFormat": "processSlots-validators"
    },
    {
     "expr": "rate(lodestar_stfn_balances_nodes_populated_miss_total{source=\"processSlots\"} [$rate_interval])\n/on(instance)\nrate(lodestar_stfn_state_cloned_count_count[$rate_interval])",
     "legendFormat": "processSlots-balances"
    }
   ]
  },
  {
   "title": "Epoch transition by reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "rate(lodestar_epoch_transition_by_caller_total[$rate_interval]) * 384",
     "legendFormat": "{{caller}}"
    }
   ]
  },
  {
   "title": "State hash_tree_root avg time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_stfn_hash_tree_root_seconds_sum[$rate_interval])\n/ on(source)\nrate(lodestar_stfn_hash_tree_root_seconds_count[$rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State hash_tree_root by bucket",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "rate(lodestar_stfn_hash_tree_root_seconds_bucket[$rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BLS worker pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 },
   "targets": [
    {}
   ]
  },
  {
   "title": "About",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 99 },
   "options": {
    "content": "Verifies signature sets in a thread pool of workers. Must ensure that signatures are verified fast and efficiently."
   },
   "targets": [
    {
     "expr": "rate(lodestar_bls_thread_pool_time_seconds_sum[$rate_interval])",
     "legendFormat": "{{workerId}}"
    }
   ]
  },
  {
   "title": "BLS thread pool - utilization rate",
   "type": "timeseries",
   "description": "Utilization rate = total CPU time per worker per second. Graph is stacked. This ratios should be high since BLS verification is the limiting factor in the node's throughput.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(lodestar_bls_thread_pool_time_seconds_sum[$rate_interval])",
     "legendFormat": "{{workerId}}"
    }
   ]
  },
  {
   "title": "Aggregated pubkeys / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "expr": "rate(lodestar_bls_aggregated_pubkeys_total[$rate_interval])",
     "legendFormat": "pubkeys / sec"
    }
   ]
  },
  {
   "title": "BLS thread pool - sig set verification time / set",
   "type": "timeseries",
   "description": "Average sync time to validate a single signature set. Note that the set may have been verified in batch. In most normal hardware this value should be ~1-2ms",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(lodestar_bls_thread_pool_time_seconds_sum[$rate_interval]))/sum(rate(lodestar_bls_thread_pool_success_jobs_signature_sets_count[$rate_interval]))",
     "legendFormat": "pool"
    }
   ]
  },
  {
   "title": "BLS thread pool - sig sets / sec",
   "type": "timeseries",
   "description": "Raw throughput of the thread pool. How many individual signature sets are successfully validated per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(lodestar_bls_thread_pool_success_jobs_signature_sets_count[$rate_interval])",
     "legendFormat": "pool"
    }
   ]
  },
  {
   "title": "BLS thread pool - queue length",
   "type": "timeseries",
   "description": "Total length of the job queue. Note: this queue is not bounded",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lodestar_bls_thread_pool_queue_length",
     "legendFormat": "pool"
    }
   ]
  },
  {
   "title": "BLS thread pool - job wait time",
   "type": "timeseries",
   "description": "How much async time job spent waiting in the job queue before being picked up. This number should be really low <100ms to ensure signatures are validated fast.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_bls_thread_pool_queue_job_wait_time_seconds_sum[$rate_interval])/rate(lodestar_bls_thread_pool_queue_job_wait_time_seconds_count[$rate_interval])",
     "legendFormat": "pool"
    }
   ]
  },
  {
   "title": "BLS worker pool - to from worker latency",
   "type": "timeseries",
   "description": "Async time from sending a message to the worker and the worker receiving it.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_bls_thread_pool_latency_to_worker_sum[6m])/rate(lodestar_bls_thread_pool_latency_to_worker_count[6m])",
     "legendFormat": "to worker"
    },
    {
     "expr": "rate(lodestar_bls_thread_pool_latency_from_worker_sum[6m])/rate(lodestar_bls_thread_pool_latency_from_worker_count[6m])",
     "legendFormat": "from worker"
    }
   ]
  },
  {
   "title": "BLS thread pool - % of sigs verified in batch",
   "type": "timeseries",
   "description": "What percentage of total signature sets were verified in batch, which is an optimization to reduce verification costs by x2. For a synced node this should be ~100%",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(lodestar_bls_thread_pool_batch_sigs_success_total[$rate_interval])/rate(lodestar_bls_thread_pool_success_jobs_signature_sets_count[$rate_interval])",
     "legendFormat": "pool"
    }
   ]
  },
  {
   "title": "BLS worker pool - sigs per set",
   "type": "timeseries",
   "description": "Average signatures per set. This number is decided by the time of object submitted to the pool:\n- Sync blocks: 128\n- Aggregates: 3\n- Attestations: 1",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(lodestar_bls_thread_pool_sig_sets_started_total[$rate_interval])/(rate(lodestar_bls_thread_pool_jobs_started_total[$rate_interval])>0)",
     "legendFormat": "pool"
    }
   ]
  },
  {
   "title": "BLS thread pool - Error rates",
   "type": "timeseries",
   "description": "How many individual signature sets are invalid vs (valid + invalid). We don't control this number since peers may send us invalid signatures. This number should be very low since we should ban bad peers. If it's too high the batch optimization may not be worth it.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(lodestar_bls_thread_pool_error_jobs_signature_sets_count[$rate_interval])\n/\n(\n    rate(lodestar_bls_thread_pool_success_jobs_signature_sets_count[$rate_interval])\n    + rate(lodestar_bls_thread_pool_error_jobs_signature_sets_count[$rate_interval])\n)",
     "legendFormat": "sig_error_rate"
    },
    {
     "expr": "rate(lodestar_bls_thread_pool_batch_retries_total[$rate_interval])",
     "legendFormat": "batch_retries"
    }
   ]
  },
  {
   "title": "BLS worker pool - sets per job",
   "type": "timeseries",
   "description": "Average sets per job. A set may contain +1 signatures. This number should be higher than 1 to reduce communication costs",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(lodestar_bls_thread_pool_jobs_started_total[$rate_interval])/rate(lodestar_bls_thread_pool_job_groups_started_total[$rate_interval])",
     "legendFormat": "pool"
    }
   ]
  },
  {
   "title": "Precompute Epoch Transition",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Run Result",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
   "targets": [
    {
     "expr": "32*12 * rate(lodestar_precompute_next_epoch_transition_result_total[13m])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Hit vs Waste",
   "type": "timeseries",
   "description": "Cache Hit Count: number of state cache hit\nWaste Count: number of state that's not used",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
   "targets": [
    {
     "expr": "rate(lodestar_precompute_next_epoch_transition_hits_total[6m])",
     "legendFormat": "Cache Hit Count"
    },
    {
     "expr": "rate(lodestar_precompute_next_epoch_transition_waste_total[6m])",
     "legendFormat": "Waste Count"
    }
   ]
  },
  {
   "title": "Skip rate + error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
   "targets": [
    {
     "expr": "sum(rate(lodestar_precompute_next_epoch_transition_result_total{result=\"skip\"}[13m]))\n/\nsum(rate(lodestar_precompute_next_epoch_transition_result_total[13m]))",
     "legendFormat": "skip rate"
    },
    {
     "expr": "sum(rate(lodestar_precompute_next_epoch_transition_result_total{result=\"error\"}[13m]))\n/\nsum(rate(lodestar_precompute_next_epoch_transition_result_total[13m]))",
     "legendFormat": "error rate"
    }
   ]
  },
  {
   "title": "Runs / epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 149 },
   "targets": [
    {
     "expr": "32*12 * sum(rate(lodestar_precompute_next_epoch_transition_result_total[13m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Prepare Next Epoch Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_precompute_next_epoch_transition_duration_seconds_sum[$rate_interval])\n/\nrate(lodestar_precompute_next_epoch_transition_duration_seconds_count[$rate_interval])",
     "legendFormat": "prepare_next_epoch_duration"
    }
   ]
  },
  {
   "title": "Prepare Next Epoch Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 157 },
   "targets": [
    {
     "expr": "rate(lodestar_precompute_next_epoch_transition_duration_seconds_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Prepare Next Epoch hash_tree_root",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 165 },
   "targets": [
    {
     "expr": "rate(lodestar_stfn_hash_tree_root_seconds_bucket{source=\"prepare_next_epoch\"}[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "GetBlobs Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 173 } },
  {
   "title": "Block availability resolution stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(beacon_datapromise_blockinputs_available_using_getblobs_total[$rate_interval])/((rate(beacon_blockinputs_already_available_total[$rate_interval]) +\nrate(beacon_datapromise_blockinputs_available_post_blobs_pull_total[$rate_interval])) or vector(1))",
     "legendFormat": "blocks used getblobs blobs"
    },
    {
     "expr": "rate(beacon_datapromise_blockinputs_tried_for_blobs_pull_total[$rate_interval])/((rate(beacon_blockinputs_already_available_total[$rate_interval]) +\nrate(beacon_datapromise_blockinputs_available_post_blobs_pull_total[$rate_interval])) or vector(1))",
     "legendFormat": "unavailable blocks at arrival"
    },
    {
     "expr": "rate(beacon_datapromise_blockinputs_available_post_blobs_pull_total[$rate_interval])/((rate(beacon_blockinputs_already_available_total[$rate_interval]) +\nrate(beacon_datapromise_blockinputs_available_post_blobs_pull_total[$rate_interval])) or vector(1))",
     "legendFormat": "blocks available from getblobs"
    },
    {
     "expr": "rate(beacon_datapromise_blockinputs_retried_and_resolved_from_network_total[$rate_interval])/((rate(beacon_blockinputs_already_available_total[$rate_interval]) +\nrate(beacon_datapromise_blockinputs_available_post_blobs_pull_total[$rate_interval])) or vector(1))",
     "legendFormat": "blocks available post still requiring req/resp"
    },
    {
     "expr": "rate(beacon_blockinputs_already_available_total[$rate_interval])/((rate(beacon_blockinputs_already_available_total[$rate_interval]) +\nrate(beacon_datapromise_blockinputs_available_post_blobs_pull_total[$rate_interval])) or vector(1))",
     "legendFormat": "already available blocks at arrival"
    },
    {
     "expr": "rate(beacon_datapromise_blockinputs_finally_available_from_reqresp_total[$rate_interval])/((rate(beacon_blockinputs_already_available_total[$rate_interval]) +\nrate(beacon_datapromise_blockinputs_available_post_blobs_pull_total[$rate_interval])) or vector(1))",
     "legendFormat": "blockinputs available from req/resp"
    },
    {
     "expr": "rate(beacon_datapromise_blockinputs_available_from_getblobs_total[$rate_interval])/((rate(beacon_blockinputs_already_available_total[$rate_interval]) +\nrate(beacon_datapromise_blockinputs_available_post_blobs_pull_total[$rate_interval])) or vector(1))",
     "legendFormat": "blockinputs available from getblobs"
    },
    {
     "expr": "rate(beacon_datapromise_blockinputs_retried_for_blobs_pull_total[$rate_interval])/((rate(beacon_blockinputs_already_available_total[$rate_interval]) +\nrate(beacon_datapromise_blockinputs_available_post_blobs_pull_total[$rate_interval])) or vector(1))",
     "legendFormat": "blocks retried for blobs"
    },
    {
     "expr": "rate(beacon_get_blobs_v1_requests_total[$rate_interval])/((rate(beacon_blockinputs_already_available_total[$rate_interval]) +\nrate(beacon_datapromise_blockinputs_available_post_blobs_pull_total[$rate_interval])) or vector(1))",
     "legendFormat": "Total number of block inputs that were tried to resolve"
    }
   ]
  },
  {
   "title": "Blob availability resolution stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(beacon_datapromise_blockinput_blobs_finally_queried_from_network_total[$rate_interval])/\n((\nrate(beacon_blockinput_blobs_already_available_total[$rate_interval]) +  \nrate(beacon_datapromise_blockinput_blobs_already_available_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_delayed_gossip_available_total[$rate_interval]) + \nrate(beacon_get_blobs_v1_blob_useful_response_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_finally_resolved_from_network_total[$rate_interval])\n) or vector(1))",
     "legendFormat": "blobs finally req/resp queried"
    },
    {
     "expr": "rate(beacon_datapromise_blockinput_blobs_finally_resolved_from_network_total[$rate_interval])/\n((\nrate(beacon_blockinput_blobs_already_available_total[$rate_interval]) +  \nrate(beacon_datapromise_blockinput_blobs_already_available_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_delayed_gossip_available_total[$rate_interval]) + \nrate(beacon_get_blobs_v1_blob_useful_response_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_finally_resolved_from_network_total[$rate_interval])\n) or vector(1))",
     "legendFormat": "blobs finally req/resp fetched"
    },
    {
     "expr": "rate(beacon_datapromise_blockinput_blobs_retried_from_network_total[$rate_interval])/\n((\nrate(beacon_blockinput_blobs_already_available_total[$rate_interval]) +  \nrate(beacon_datapromise_blockinput_blobs_already_available_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_delayed_gossip_available_total[$rate_interval]) + \nrate(beacon_get_blobs_v1_blob_useful_response_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_finally_resolved_from_network_total[$rate_interval])\n) or vector(1))",
     "legendFormat": "total blobs retried"
    },
    {
     "expr": "rate(beacon_datapromise_blockinput_blobs_retried_and_resolved_from_network_total[$rate_interval])/\n((\nrate(beacon_blockinput_blobs_already_available_total[$rate_interval]) +  \nrate(beacon_datapromise_blockinput_blobs_already_available_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_delayed_gossip_available_total[$rate_interval]) + \nrate(beacon_get_blobs_v1_blob_useful_response_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_finally_resolved_from_network_total[$rate_interval])\n) or vector(1))",
     "legendFormat": "total blobs retried and resolved"
    },
    {
     "expr": "rate(beacon_datapromise_blockinput_blobs_delayed_gossip_available_total[$rate_interval])/\n((\nrate(beacon_blockinput_blobs_already_available_total[$rate_interval]) +  \nrate(beacon_datapromise_blockinput_blobs_already_available_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_delayed_gossip_available_total[$rate_interval]) + \nrate(beacon_get_blobs_v1_blob_useful_response_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_finally_resolved_from_network_total[$rate_interval])\n) or vector(1))",
     "legendFormat": "delayed gossip blobs available"
    },
    {
     "expr": "rate(beacon_get_blobs_v1_blob_returned_but_arrived_during_response_total[$rate_interval])/\n((\nrate(beacon_blockinput_blobs_already_available_total[$rate_interval]) +  \nrate(beacon_datapromise_blockinput_blobs_already_available_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_delayed_gossip_available_total[$rate_interval]) + \nrate(beacon_get_blobs_v1_blob_useful_response_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_finally_resolved_from_network_total[$rate_interval])\n) or vector(1))",
     "legendFormat": "delayed gossip blobs used"
    },
    {
     "expr": "rate(beacon_get_blobs_v1_blob_useful_response_total[$rate_interval])/\n((\nrate(beacon_blockinput_blobs_already_available_total[$rate_interval]) +  \nrate(beacon_datapromise_blockinput_blobs_already_available_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_delayed_gossip_available_total[$rate_interval]) + \nrate(beacon_get_blobs_v1_blob_useful_response_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_finally_resolved_from_network_total[$rate_interval])\n) or vector(1))",
     "legendFormat": "actual useful blobs (not delayed goissip available)"
    },
    {
     "expr": "rate(beacon_blockinput_blobs_already_available_total[$rate_interval])/\n((\nrate(beacon_blockinput_blobs_already_available_total[$rate_interval]) +  \nrate(beacon_datapromise_blockinput_blobs_already_available_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_delayed_gossip_available_total[$rate_interval]) + \nrate(beacon_get_blobs_v1_blob_useful_response_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_finally_resolved_from_network_total[$rate_interval])\n) or vector(1))",
     "legendFormat": "blobs of already available blocks"
    }
   ]
  },
  {
   "title": "GetBlobs API Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(beacon_get_blobs_v1_requested_blobs_count_total[$rate_interval])/\n((\nrate(beacon_blockinput_blobs_already_available_total[$rate_interval]) +  \nrate(beacon_datapromise_blockinput_blobs_already_available_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_delayed_gossip_available_total[$rate_interval]) + \nrate(beacon_get_blobs_v1_blob_useful_response_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_finally_resolved_from_network_total[$rate_interval])\n) or vector(1))",
     "legendFormat": "total blobs queried in api"
    },
    {
     "expr": "rate(beacon_get_blobs_v1_blob_returned_response_total[$rate_interval])/\n((\nrate(beacon_blockinput_blobs_already_available_total[$rate_interval]) +  \nrate(beacon_datapromise_blockinput_blobs_already_available_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_delayed_gossip_available_total[$rate_interval]) + \nrate(beacon_get_blobs_v1_blob_useful_response_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_finally_resolved_from_network_total[$rate_interval])\n) or vector(1))",
     "legendFormat": "blobs available"
    },
    {
     "expr": "rate(beacon_get_blobs_v1_missing_blob_response_total[$rate_interval])/\n((\nrate(beacon_blockinput_blobs_already_available_total[$rate_interval]) +  \nrate(beacon_datapromise_blockinput_blobs_already_available_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_delayed_gossip_available_total[$rate_interval]) + \nrate(beacon_get_blobs_v1_blob_useful_response_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_finally_resolved_from_network_total[$rate_interval])\n) or vector(1))",
     "legendFormat": "blobs not available"
    },
    {
     "expr": "rate(beacon_get_blobs_v1_response_error_total[$rate_interval])/\n((\nrate(beacon_blockinput_blobs_already_available_total[$rate_interval]) +  \nrate(beacon_datapromise_blockinput_blobs_already_available_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_delayed_gossip_available_total[$rate_interval]) + \nrate(beacon_get_blobs_v1_blob_useful_response_total[$rate_interval]) + \nrate(beacon_datapromise_blockinput_blobs_finally_resolved_from_network_total[$rate_interval])\n) or vector(1))",
     "legendFormat": "blobs errored"
    }
   ]
  },
  {
   "title": "Blobs published to gossip / slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 182 },
   "targets": [
    {
     "expr": "12*rate(lodestar_gossip_blob_published_from_engine_total[$rate_interval])",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Getblobs cache stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(beacon_datapromise_blockinput_blobs_found_nonnull_in_getblobs_cache_total[$rate_interval])/((rate(beacon_datapromise_blockinput_blobs_notfound_in_getblobs_cache_total[$rate_interval])+\nrate(beacon_datapromise_blockinput_blobs_found_null_in_getblobs_cache_total[$rate_interval])+\nrate(beacon_datapromise_blockinput_blobs_found_nonnull_in_getblobs_cache_total[$rate_interval])\n) or vector(1))",
     "legendFormat": "old blobs found in getblobs cache"
    },
    {
     "expr": "rate(beacon_datapromise_blockinput_blobs_found_null_in_getblobs_cache_total[$rate_interval])/((rate(beacon_datapromise_blockinput_blobs_notfound_in_getblobs_cache_total[$rate_interval])+\nrate(beacon_datapromise_blockinput_blobs_found_null_in_getblobs_cache_total[$rate_interval])+\nrate(beacon_datapromise_blockinput_blobs_found_nonnull_in_getblobs_cache_total[$rate_interval])\n) or vector(1))",
     "legendFormat": "old unavailable blobs but null in getblobs cache"
    },
    {
     "expr": "rate(beacon_datapromise_blockinput_blobs_notfound_in_getblobs_cache_total[$rate_interval])/((rate(beacon_datapromise_blockinput_blobs_notfound_in_getblobs_cache_total[$rate_interval])+\nrate(beacon_datapromise_blockinput_blobs_found_null_in_getblobs_cache_total[$rate_interval])+\nrate(beacon_datapromise_blockinput_blobs_found_nonnull_in_getblobs_cache_total[$rate_interval])\n) or vector(1))",
     "legendFormat": "new unavailable blobs for getblobs"
    }
   ]
  },
  {
   "title": "Cache size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 190 },
   "targets": [
    { "expr": "getblob_cache_size", "legendFormat": "getblob cache size" },
    {
     "expr": "beacon_datapromise_blockinput_retry_tracker_cache_size",
     "legendFormat": "blockinput retry cache size"
    }
   ]
  },
  {
   "title": "Cache prune rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 198 },
   "targets": [
    {
     "expr": "rate(getblob_cache_pruned_total[$rate_interval])",
     "legendFormat": "getblob cache pruned"
    },
    {
     "expr": "rate(beacon_datapromise_blockinput_retry_tracker_cache_pruned[$rate_interval])",
     "legendFormat": "blockinput retry cache pruned"
    }
   ]
  },
  { "title": "Gossip Block", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 206 } },
  {
   "title": "Block recv delay",
   "type": "heatmap",
   "description": "Time elapsed between block slot time and the time block received via gossip",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 207 },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_elapsed_time_till_received_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Block process delay",
   "type": "heatmap",
   "description": "Time elapsed between block slot time and the time block processed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 207 },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_elapsed_time_till_processed_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Avg block recv delay",
   "type": "timeseries",
   "description": "Time elapsed between block slot time and the time block received via gossip",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 215 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_elapsed_time_till_received_sum[$rate_interval]) / rate(lodestar_gossip_block_elapsed_time_till_received_count[$rate_interval])",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Avg block process delay",
   "type": "timeseries",
   "description": "Time elapsed between block slot time and the time block processed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 215 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_elapsed_time_till_processed_sum[$rate_interval]) / rate(lodestar_gossip_block_elapsed_time_till_processed_count[$rate_interval])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Block recv to gossip validation delay",
   "type": "heatmap",
   "description": "Time elapsed between block received and block validated",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 223 },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_received_to_gossip_validate_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Gossip validation time",
   "type": "heatmap",
   "description": "Time to apply gossip validations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 223 },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_gossip_validate_time_bucket[$rate_interval])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Avg block recv to gossip validation delay",
   "type": "timeseries",
   "description": "Time elapsed between block received and block validated",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 231 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_received_to_gossip_validate_sum[$rate_interval]) / rate(lodestar_gossip_block_received_to_gossip_validate_count[$rate_interval])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Avg gossip validation time",
   "type": "timeseries",
   "description": "Time to apply gossip validations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 231 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_gossip_validate_time_sum[$rate_interval]) / rate(lodestar_gossip_block_gossip_validate_time_count[$rate_interval])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Block recv to state transition delay",
   "type": "heatmap",
   "description": "Time elapsed between block received and block state transition",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 239 },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_received_to_state_transition_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Block state transition",
   "type": "heatmap",
   "description": "Time to validate block state transition",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 239 },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_state_transition_time_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Avg block recv to state transition delay",
   "type": "timeseries",
   "description": "Time elapsed between block received and block state transition",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 247 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_received_to_state_transition_sum[$rate_interval]) / rate(lodestar_gossip_block_received_to_state_transition_count[$rate_interval])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Avg block state transition",
   "type": "timeseries",
   "description": "Time to validate block state transition",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 247 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_state_transition_time_sum[$rate_interval]) / rate(lodestar_gossip_block_state_transition_time_count[$rate_interval])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Block recv to sig verification delay",
   "type": "heatmap",
   "description": "Time elapsed between block received and block signatures verification",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 255 },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_received_to_signatures_verification_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Block sig verification",
   "type": "heatmap",
   "description": "Time elapsed for block signatures verification",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 255 },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_signatures_verification_time_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Avg block recv to sig verification delay",
   "type": "timeseries",
   "description": "Time elapsed between block received and block signatures verification",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 263 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_received_to_signatures_verification_sum[$rate_interval]) / rate(lodestar_gossip_block_received_to_signatures_verification_count[$rate_interval])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Avg block sig verification",
   "type": "timeseries",
   "description": "Time elapsed for block signatures verification",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 263 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_signatures_verification_time_sum[$rate_interval]) / rate(lodestar_gossip_block_signatures_verification_time_count[$rate_interval])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Block recv to execution payload verification delay",
   "type": "heatmap",
   "description": "Time elapsed between block received and execution payload verification",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 271 },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_received_to_execution_payload_verification_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Block execution payload verification",
   "type": "heatmap",
   "description": "Time elapsed for execution payload verification",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 271 },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_execution_payload_verification_time_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Avg block recv to execution payload verification delay",
   "type": "timeseries",
   "description": "Time elapsed between block received and execution payload verification",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 279 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_received_to_execution_payload_verification_sum[$rate_interval]) / rate(lodestar_gossip_block_received_to_execution_payload_verification_count[$rate_interval])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Avg block execution payload verification",
   "type": "timeseries",
   "description": "Time elapsed for execution payload verification",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 279 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_execution_payload_verification_time_sum[$rate_interval]) / rate(lodestar_gossip_execution_payload_verification_time_count[$rate_interval])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Block recv to import delay",
   "type": "heatmap",
   "description": "Time elapsed between block received and block import",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 287 },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_received_to_block_import_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Block import",
   "type": "heatmap",
   "description": "Time elapsed for block import",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 287 },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_block_import_time_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Avg block recv to import delay",
   "type": "timeseries",
   "description": "Time elapsed between block received and block import",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 295 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_received_to_block_import_sum[$rate_interval]) / rate(lodestar_gossip_block_received_to_block_import_count[$rate_interval])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Avg block import",
   "type": "timeseries",
   "description": "Time elapsed for block import",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 295 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_block_import_time_sum[$rate_interval]) / rate(lodestar_gossip_block_block_import_time_count[$rate_interval])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Block recv to blob availability delay",
   "type": "heatmap",
   "description": "Time elapsed between block received and blobs became available",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 303 },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_received_to_blobs_availability_time_bucket[$rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block verified to blob availability delay",
   "type": "heatmap",
   "description": "Time elapsed between block verified and blobs became available",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 303 },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_verified_to_blobs_availability_time_bucket[$rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg block recv to blob availability delay",
   "type": "timeseries",
   "description": "Time elapsed between block received and blobs became available",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 311 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_received_to_blobs_availability_time_sum[$rate_interval]) / rate(lodestar_gossip_block_received_to_blobs_availability_time_count[$rate_interval])",
     "legendFormat": "{{numBlobs}} blobs"
    }
   ]
  },
  {
   "title": "Avg block verified to blob availability delay",
   "type": "timeseries",
   "description": "Time elapsed between block verified and blobs became available",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 311 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_gossip_block_verified_to_blobs_availability_time_sum[$rate_interval]) / rate(lodestar_gossip_block_verified_to_blobs_availability_time_count[$rate_interval])",
     "legendFormat": "{{numBlobs}} blobs"
    }
   ]
  }
 ]
}