{
 "title": "Lodestar - block production",
 "tags": [ "lodestar" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "rate_interval",
    "label": "rate() interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Block Production",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Full block production avg time with steps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_block_production_execution_steps_seconds_sum{step=\"proposerSlashing\"}[$rate_interval])\n/\nrate(beacon_block_production_execution_steps_seconds_count{step=\"proposerSlashing\"}[$rate_interval])",
     "legendFormat": "{{step}}"
    },
    {
     "expr": "rate(beacon_block_production_execution_steps_seconds_sum{step=\"attesterSlashings\"}[$rate_interval])\n/\nrate(beacon_block_production_execution_steps_seconds_count{step=\"attesterSlashings\"}[$rate_interval])",
     "legendFormat": "{{step}}"
    },
    {
     "expr": "rate(beacon_block_production_execution_steps_seconds_sum{step=\"voluntaryExits\"}[$rate_interval])\n/\nrate(beacon_block_production_execution_steps_seconds_count{step=\"voluntaryExits\"}[$rate_interval])",
     "legendFormat": "{{step}}"
    },
    {
     "expr": "rate(beacon_block_production_execution_steps_seconds_sum{step=\"blsToExecutionChanges\"}[$rate_interval])\n/\nrate(beacon_block_production_execution_steps_seconds_count{step=\"blsToExecutionChanges\"}[$rate_interval])",
     "legendFormat": "{{step}}"
    },
    {
     "expr": "rate(beacon_block_production_execution_steps_seconds_sum{step=\"attestations\"}[$rate_interval])\n/\nrate(beacon_block_production_execution_steps_seconds_count{step=\"attestations\"}[$rate_interval])",
     "legendFormat": "{{step}}"
    },
    {
     "expr": "rate(beacon_block_production_execution_steps_seconds_sum{step=\"syncAggregate\"}[$rate_interval])\n/\nrate(beacon_block_production_execution_steps_seconds_count{step=\"syncAggregate\"}[$rate_interval])",
     "legendFormat": "{{step}}"
    },
    {
     "expr": "rate(beacon_block_production_execution_steps_seconds_sum{step=\"executionPayload\"}[$rate_interval])\n/\nrate(beacon_block_production_execution_steps_seconds_count{step=\"executionPayload\"}[$rate_interval])",
     "legendFormat": "{{step}}"
    }
   ]
  },
  {
   "title": "Blinded block production avg time with steps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_block_production_builder_steps_seconds_sum{step=\"proposerSlashing\"}[$rate_interval])\n/\nrate(beacon_block_production_builder_steps_seconds_count{step=\"proposerSlashing\"}[$rate_interval])",
     "legendFormat": "{{step}}"
    },
    {
     "expr": "rate(beacon_block_production_builder_steps_seconds_sum{step=\"attesterSlashings\"}[$rate_interval])\n/\nrate(beacon_block_production_builder_steps_seconds_count{step=\"attesterSlashings\"}[$rate_interval])",
     "legendFormat": "{{step}}"
    },
    {
     "expr": "rate(beacon_block_production_builder_steps_seconds_sum{step=\"voluntaryExits\"}[$rate_interval])\n/\nrate(beacon_block_production_builder_steps_seconds_count{step=\"voluntaryExits\"}[$rate_interval])",
     "legendFormat": "{{step}}"
    },
    {
     "expr": "rate(beacon_block_production_builder_steps_seconds_sum{step=\"blsToExecutionChanges\"}[$rate_interval])\n/\nrate(beacon_block_production_builder_steps_seconds_count{step=\"blsToExecutionChanges\"}[$rate_interval])",
     "legendFormat": "{{step}}"
    },
    {
     "expr": "rate(beacon_block_production_builder_steps_seconds_sum{step=\"attestations\"}[$rate_interval])\n/\nrate(beacon_block_production_builder_steps_seconds_count{step=\"attestations\"}[$rate_interval])",
     "legendFormat": "{{step}}"
    },
    {
     "expr": "rate(beacon_block_production_builder_steps_seconds_sum{step=\"syncAggregate\"}[$rate_interval])\n/\nrate(beacon_block_production_builder_steps_seconds_count{step=\"syncAggregate\"}[$rate_interval])",
     "legendFormat": "{{step}}"
    },
    {
     "expr": "rate(beacon_block_production_builder_steps_seconds_sum{step=\"executionPayload\"}[$rate_interval])\n/\nrate(beacon_block_production_builder_steps_seconds_count{step=\"executionPayload\"}[$rate_interval])",
     "legendFormat": "{{step}}"
    }
   ]
  },
  {
   "title": "Success + Error rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(beacon_block_production_successes_total{source=\"engine\"}[$rate_interval])",
     "legendFormat": "engine success"
    },
    {
     "expr": "rate(beacon_block_production_requests_total{source=\"engine\"}[$rate_interval])\n-\nrate(beacon_block_production_successes_total{source=\"engine\"}[$rate_interval])",
     "legendFormat": "engine errors"
    },
    {
     "expr": "-1 * rate(beacon_block_production_successes_total{source=\"builder\"}[$rate_interval])",
     "legendFormat": "builder success"
    },
    {
     "expr": "-1 *\n(\n    rate(beacon_block_production_requests_total{source=\"builder\"}[$rate_interval])\n    -\n    rate(beacon_block_production_successes_total{source=\"builder\"}[$rate_interval])\n)",
     "legendFormat": "builder errors"
    }
   ]
  },
  {
   "title": "Block production avg time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_block_production_seconds_sum[$rate_interval])\n/\nrate(beacon_block_production_seconds_count[$rate_interval])",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Block Proposal Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(lodestar_api_rest_errors_total{operationId=~\"produceBlockV3|publishBlockV2|publishBlindedBlockV2\"}[$rate_interval])",
     "legendFormat": "{{operationId}}"
    }
   ]
  },
  {
   "title": "Block production time histogram",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(beacon_block_production_seconds_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Consensus block value average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(beacon_block_production_consensus_block_value_sum[$rate_interval]))\n/\nsum(rate(beacon_block_production_consensus_block_value_count[$rate_interval]))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Consensus block value histogram",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(beacon_block_production_consensus_block_value_bucket[$rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Op-pool sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "lodestar_oppool_aggregated_attestation_pool_size",
     "legendFormat": "aggregated_attestation"
    },
    {
     "expr": "lodestar_oppool_aggregated_attestation_pool_unique_data_count",
     "legendFormat": "aggregated_attestation_unique"
    },
    {
     "expr": "lodestar_oppool_attestation_pool_size",
     "legendFormat": "attestation"
    },
    {
     "expr": "lodestar_oppool_attester_slashing_pool_size",
     "legendFormat": "attester_slashing"
    },
    {
     "expr": "lodestar_oppool_proposer_slashing_pool_size",
     "legendFormat": "proposer_slashing"
    },
    {
     "expr": "lodestar_oppool_voluntary_exit_pool_size",
     "legendFormat": "voluntary_exit"
    },
    {
     "expr": "lodestar_oppool_sync_committee_message_pool_size",
     "legendFormat": "sync_committee_message"
    },
    {
     "expr": "lodestar_oppool_sync_contribution_and_proof_pool_pool_size",
     "legendFormat": "sync_contribution_and_proof"
    }
   ]
  },
  {
   "title": "Builder API queries / slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "12 * rate(lodestar_builder_http_client_request_time_seconds_count[$rate_interval])",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Builder API request times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_builder_http_client_request_time_seconds_sum[$rate_interval])\n/\nrate(lodestar_builder_http_client_request_time_seconds_count[$rate_interval])",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "All Validators Block Proposal Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "lodestar_all_validators_total_count"
    },
    {
     "expr": "lodestar_all_validators_finalized_count"
    },
    {
     "expr": "lodestar_all_validators_orphaned_count"
    },
    {
     "expr": "lodestar_all_validators_missed_count"
    }
   ]
  },
  {
   "title": "Attached Validators Block Proposal Data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "384*rate(validator_monitor_prev_epoch_block_proposal_summary[$rate_interval])",
     "legendFormat": "{{summary}}"
    }
   ]
  },
  {
   "title": "Finalized Canonical Checkpoints",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "lodestar_finalized_canonical_checkpoints_count"
    },
    {
     "expr": "lodestar_finalized_found_checkpoints_in_state_cache"
    }
   ]
  },
  {
   "title": "Attached Proposers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lodestar_finalized_attached_validators_count"
    }
   ]
  },
  {
   "title": "Request Next Epoch Proposal Duties",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "rate(lodestar_duties_request_next_epoch_proposal_duties_hit_total[$rate_interval])",
     "legendFormat": "hit"
    },
    {
     "expr": "lodestar_duties_request_next_epoch_proposal_duties_miss_total",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Reason of building on head block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "rate(beacon_fork_choice_not_reorged_reason_total[$rate_interval])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Weak head blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "rate(beacon_weak_head_detected_total[$rate_interval])",
     "legendFormat": "weak head"
    }
   ]
  },
  { "title": "Produced Aggregate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Produced Aggregate Participants Histogram",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "rate(lodestar_produced_aggregate_participants_bucket[$rate_interval]) * 12",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Produced Sync Contribution Participants Histogram",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "rate(lodestar_produced_sync_contribution_participants_bucket[$rate_interval]) * 12",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Produced Aggregate Participants",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "rate(lodestar_produced_aggregate_participants_sum[$rate_interval])\n/\nrate(lodestar_produced_aggregate_participants_count[$rate_interval])",
     "legendFormat": "Aggregate"
    },
    {
     "expr": "rate(lodestar_produced_sync_contribution_participants_sum[$rate_interval])\n/\nrate(lodestar_produced_sync_contribution_participants_count[$rate_interval])",
     "legendFormat": "Sync Contribution"
    }
   ]
  },
  {
   "title": "Aggregate cache misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "rate(lodestar_oppool_attestation_pool_get_aggregate_cache_misses_total[$rate_interval])",
     "legendFormat": "cache misses"
    }
   ]
  },
  { "title": "Packed Attestations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "New Seen Attesters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "lodestar_stfn_new_seen_attesters_per_block_total",
     "legendFormat": "on_chain"
    },
    {
     "expr": "lodestar_oppool_aggregated_attestation_pool_packed_attestations_new_seen_attesters_total",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Scanned Slots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "lodestar_oppool_aggregated_attestation_pool_packed_attestations_scanned_slots_total",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "lodestar_oppool_aggregated_attestation_pool_packed_attestations_pool_slots_total",
     "legendFormat": "pool_slot"
    }
   ]
  },
  {
   "title": "Committee Count by index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "lodestar_oppool_aggregated_attestation_pool_packed_attestations_committee_count",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Total Attesters by index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "targets": [
    {
     "expr": "lodestar_oppool_aggregated_attestation_pool_packed_attestations_attesters_total",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Inclusion Distance by index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "lodestar_oppool_aggregated_attestation_pool_packed_attestations_inclusion_distance_total",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Non participant by index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "targets": [
    {
     "expr": "lodestar_oppool_aggregated_attestation_pool_packed_attestations_non_participation_total",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Invalid AttestationData",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "lodestar_oppool_aggregated_attestation_pool_packed_attestations_invalid_attestation_data_total",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "lodestar_oppool_aggregated_attestation_pool_packed_attestations_empty_attestation_data_total",
     "legendFormat": "empty_attestation_data"
    }
   ]
  },
  {
   "title": "Returned Attestations by slot delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "targets": [
    {
     "expr": "lodestar_oppool_aggregated_attestation_pool_packed_attestations_returned_attestations_total",
     "legendFormat": "{{inclusionDistance}}"
    }
   ]
  },
  {
   "title": "Scanned Attestations by slot delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "targets": [
    {
     "expr": "lodestar_oppool_aggregated_attestation_pool_packed_attestations_scanned_attestations_total",
     "legendFormat": "{{inclusionDistance}}"
    }
   ]
  },
  { "title": "Aggregated Attestation Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 } },
  {
   "title": "Aggregated Attestation Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "targets": [
    {
     "expr": "lodestar_oppool_aggregated_attestation_pool_size",
     "legendFormat": "size"
    },
    {
     "expr": "lodestar_oppool_aggregated_attestation_pool_unique_data_count",
     "legendFormat": "unique_data"
    },
    {
     "expr": "lodestar_oppool_aggregated_attestation_pool_attestation_data_per_slot_total",
     "legendFormat": "att_data_per_slot"
    },
    {
     "expr": "lodestar_oppool_aggregated_attestation_pool_committees_per_slot_total",
     "legendFormat": "committees_per_slot"
    },
    {
     "expr": "lodestar_oppool_aggregated_attestation_pool_max_attestations_per_committee",
     "legendFormat": "max_attestations_per_committee"
    },
    {
     "expr": "rate(lodestar_oppool_aggregated_attestation_pool_attestations_per_committee_sum[$rate_interval])\n/\nrate(lodestar_oppool_aggregated_attestation_pool_attestations_per_committee_count[$rate_interval])",
     "legendFormat": "attestations_per_committee"
    }
   ]
  },
  {
   "title": "Gossip Insert Outcome",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "targets": [
    {
     "expr": "rate(lodestar_oppool_aggregated_attestation_pool_gossip_insert_outcome_total[$rate_interval])",
     "legendFormat": "{{insertOutcome}}"
    }
   ]
  },
  {
   "title": "Api Insert Outcome",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "targets": [
    {
     "expr": "rate(lodestar_oppool_aggregated_attestation_pool_api_insert_outcome_total[$rate_interval])",
     "legendFormat": "{{insertOutcome}}"
    }
   ]
  },
  { "title": "Sync Contribution Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 } },
  {
   "title": "Sync Contribution Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "targets": [
    {
     "expr": "lodestar_oppool_sync_contribution_and_proof_pool_size",
     "legendFormat": "size"
    },
    {
     "expr": "lodestar_oppool_sync_contribution_and_proof_pool_block_roots_per_slot_total",
     "legendFormat": "roots_per_slot"
    }
   ]
  },
  {
   "title": "Get aggregate for block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "targets": [
    {
     "expr": "lodestar_oppool_sync_contribution_and_proof_pool_get_aggregate_roots_total",
     "legendFormat": "roots"
    },
    {
     "expr": "lodestar_oppool_sync_contribution_and_proof_pool_get_aggregate_subnets_total",
     "legendFormat": "subnets"
    },
    {
     "expr": "lodestar_oppool_sync_contribution_and_proof_pool_get_aggregate_participants_total",
     "legendFormat": "participants"
    },
    {
     "expr": "lodestar_oppool_sync_contribution_and_proof_pool_get_aggregate_returns_empty_total",
     "legendFormat": "returns_empty"
    }
   ]
  },
  {
   "title": "Subnets per block root",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "targets": [
    {
     "expr": "lodestar_oppool_sync_contribution_and_proof_pool_subnets_by_block_root_total",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Participants per block root",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
   "targets": [
    {
     "expr": "lodestar_oppool_sync_contribution_and_proof_pool_participants_by_block_root_total",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Gossip Insert Outcome",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "targets": [
    {
     "expr": "rate(lodestar_oppool_sync_contribution_and_proof_pool_gossip_insert_outcome_total[$rate_interval])",
     "legendFormat": "{{insertOutcome}}"
    }
   ]
  },
  {
   "title": "Api Insert Outcome",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
   "targets": [
    {
     "expr": "rate(lodestar_oppool_sync_contribution_and_proof_pool_api_insert_outcome_total[$rate_interval])",
     "legendFormat": "{{insertOutcome}}"
    }
   ]
  }
 ]
}