{
 "title": "Lodestar - execution engine",
 "tags": [ "lodestar" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "rate_interval",
    "label": "rate() interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Engine job processor stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Engine processor queue - Utilization rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(lodestar_engine_http_processor_queue_job_time_seconds_sum[$rate_interval])",
     "legendFormat": "engine_processor"
    }
   ]
  },
  {
   "title": "Engine processor queue - Jobs / slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "12*rate(lodestar_engine_http_processor_queue_job_time_seconds_count[6m])",
     "legendFormat": "engine_processor"
    }
   ]
  },
  {
   "title": "Engine processor queue - Job time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_engine_http_processor_queue_job_time_seconds_sum[$rate_interval])/rate(lodestar_engine_http_processor_queue_job_time_seconds_count[$rate_interval])",
     "legendFormat": "engine_processor"
    }
   ]
  },
  {
   "title": "Engine processor queue - Dropped jobs %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(lodestar_engine_http_processor_queue_dropped_jobs_total[$rate_interval])/(rate(lodestar_engine_http_processor_queue_job_time_seconds_count[$rate_interval])+rate(lodestar_engine_http_processor_queue_dropped_jobs_total[$rate_interval]))",
     "legendFormat": "engine_processor"
    }
   ]
  },
  {
   "title": "Engine processor queue - Job wait time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_engine_http_processor_queue_job_wait_time_seconds_sum[$rate_interval])/rate(lodestar_engine_http_processor_queue_job_wait_time_seconds_count[$rate_interval])",
     "legendFormat": "engine_processor"
    }
   ]
  },
  {
   "title": "Engine processor queue - Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lodestar_engine_http_processor_queue_length",
     "legendFormat": "engine_processor"
    }
   ]
  },
  {
   "title": "Execution Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests / slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "12*rate(lodestar_execution_engine_http_client_request_time_seconds_count[32m])",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Urls",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lodestar_execution_engine_http_client_config_urls_count",
     "legendFormat": "execution_engine_http_client_config_urls_count"
    }
   ]
  },
  {
   "title": "Active requests",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lodestar_execution_engine_http_client_active_requests",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Request retries rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(lodestar_execution_engine_http_client_request_retries_total[$rate_interval])",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Avg request durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_execution_engine_http_client_request_time_seconds_sum[32m])\n/\nrate(lodestar_execution_engine_http_client_request_time_seconds_count[32m])",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Error rates",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(lodestar_execution_engine_http_client_request_errors_total[$rate_interval])",
     "legendFormat": "{{routeId}}"
    },
    {
     "expr": "rate(lodestar_execution_engine_http_client_request_used_fallback_url_total[$rate_interval])",
     "legendFormat": "{{routeId}} used_fallback_url"
    }
   ]
  },
  {
   "title": "Request Time > 1s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(rate(lodestar_execution_engine_http_client_request_time_seconds_bucket{le=\"1\"}[32m])) by (routeId) / sum(rate(lodestar_execution_engine_http_client_request_time_seconds_count[32m])) by (routeId)",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "notifyNewPayload / notifyForkchoiceUpdate result",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "rate(lodestar_execution_engine_notify_new_payload_result_total[1h])",
     "legendFormat": "newPayload_{{result}}"
    },
    {
     "expr": "rate(lodestar_execution_engine_notify_forkchoice_update_result_total[1h])",
     "legendFormat": "fcu_{{result}}"
    }
   ]
  },
  { "title": "Geth Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "newPayloadV2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rpc_duration_engine_newPayloadV2_success",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "newPayloadV2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rpc_duration_engine_newPayloadV2_success",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "forkchoiceUpdatedV2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rpc_duration_engine_forkchoiceUpdatedV2_success",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}