{
 "title": "Lodestar - discv5",
 "tags": [ "lodestar" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "rate_interval",
    "label": "rate() interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Discv5 Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Discovered ENR Relevancy Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(lodestar_discv5_discovered_status_total_count[$rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Connected Peer Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lodestar_discv5_connected_peer_count",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "onDiscovered result",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(lodestar_discovery_discovered_status_total_count[$rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "dial attempt rate / second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(lodestar_discovery_total_dial_attempts[$rate_interval])"
    }
   ]
  },
  {
   "title": "Received Message Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(lodestar_discv5_rcvd_message_count[$rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "dial error rate (cumulative)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(lodestar_discovery_dial_time_seconds_count{status=\"error\"})/sum(lodestar_discovery_dial_time_seconds_count)"
    }
   ]
  },
  {
   "title": "Sent Message Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(lodestar_discv5_sent_message_count[$rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "FINDNODE query avg time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_discovery_find_node_query_time_seconds_sum[$rate_interval])/rate(lodestar_discovery_find_node_query_time_seconds_count[$rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Active Session Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lodestar_discv5_active_session_count",
     "legendFormat": "sessions"
    }
   ]
  },
  {
   "title": "FINDNODE requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(lodestar_discovery_find_node_query_requests_total[$rate_interval])",
     "legendFormat": "{{action}}"
    },
    {
     "expr": "rate(lodestar_discv5_lookup_count[$rate_interval])",
     "legendFormat": "lookups"
    }
   ]
  },
  {
   "title": "Cached ENRs set size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lodestar_discovery_cached_enrs_size",
     "legendFormat": "ENR count"
    }
   ]
  },
  {
   "title": "KAD Table Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "lodestar_discv5_kad_table_size", "legendFormat": "ENR count" }
   ]
  },
  {
   "title": "dial time seconds",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_discovery_dial_time_seconds_sum[$rate_interval])/rate(lodestar_discovery_dial_time_seconds_count[$rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Not dropped rate of useful ENRs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(lodestar_discovery_discovered_status_total_count{status=~\"attempt_dial|cached\"}[$rate_interval]))\n/\nsum(rate(lodestar_discovery_discovered_status_total_count{status=~\"dropped|attempt_dial|cached\"}[$rate_interval]))"
    }
   ]
  },
  {
   "title": "Useful ENRs rate vs all seen ENRs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(lodestar_discovery_discovered_status_total_count{status=~\"dropped|attempt_dial|cached\"}[$rate_interval]))\n/\nsum(rate(lodestar_discovery_discovered_status_total_count[$rate_interval]))"
    }
   ]
  },
  {
   "title": "ENRs returned per query",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(lodestar_discovery_find_node_query_enrs_total[$rate_interval])\n/\nrate(lodestar_discovery_find_node_query_time_seconds_count[$rate_interval])",
     "legendFormat": "enrs"
    }
   ]
  },
  { "title": "Worker VM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Heap Space Used + external_memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "discv5_worker_nodejs_heap_space_size_used_bytes",
     "legendFormat": "{{space}}"
    },
    {
     "expr": "discv5_worker_nodejs_external_memory_bytes",
     "legendFormat": "external_memory"
    }
   ]
  },
  { "title": "ENR decoding", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "ENR decode error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(lodestar_discv5_decode_enr_error_count[$rate_interval]) / rate(lodestar_discv5_decode_enr_attempt_count[$rate_interval])",
     "legendFormat": "error rate"
    }
   ]
  },
  {
   "title": "ENR decode attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "rate(lodestar_discv5_decode_enr_error_count[$rate_interval])",
     "legendFormat": "errors"
    },
    {
     "expr": "rate(lodestar_discv5_decode_enr_attempt_count[$rate_interval])",
     "legendFormat": "attempts"
    }
   ]
  },
  {
   "title": "Active Resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "discv5_worker_nodejs_active_resources",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "GC pause time rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(discv5_worker_nodejs_gc_duration_seconds_sum[$rate_interval])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Active Handles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "discv5_worker_nodejs_active_handles",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "discv5_worker_nodejs_eventloop_lag_seconds",
     "legendFormat": "event loop lag"
    }
   ]
  }
 ]
}